README.md, whisperx/transcribe.py
Hello,
I've added a necessary argument to include hugging face access token which is required to load the PyAnnote pipelines
=> Added arguments and instructions to enable the usage VAD and Diarization

.github/FUNDING.yml
Hey @m-bain, you can make the sponsor link more visible by adding this file to the repo and then go to the repo settings and activate "sponsorships"
=> Add sponsor link to sidebar

README.md
imo the ticked checkboxes are more appropriate instead of strike through text.
=> doc: format checklist

whisperx/alignment.py
Hi, I initially added and tested the arabic model by @jonatasgrosman and it worked as expected, and since his models were used in other languages before and I tested the arabic model myself, I assumed it's safe to include all the available models.
=> Add more languages to models list

whisperx/alignment.py
tested and it works, this is the best available turkish model on HF, I'm also working on a script/notebook for the community to use in order to test different models and report the WER results and whether it works or not in order to speed up the language addition process
=> added turkish wav2vec2 model

whisperx/transcribe.py
Inspired by https://github.com/m-bain/whisperX/pull/91.
I have divided the inference loop into three separate loops in order to prevent the simultaneous loading of all the models. This approach will prove to be highly beneficial when transcribing multiple audio files.
=> Optimize the inference process and reduce the memory usage

whisperx/asr.py
=> add num_workers to fix pickling error

whisperx/asr.py
=> Pad language detection if audio is too short

whisperx/alignment.py, whisperx/transcribe.py
This fix gets diarization to work in v3.
=> references #202, attempt to fix speaker diarization failing in v3

.gitignore, Dockerfile, README.md, notebooks/whisperx.ipynb
=> feat: adding the docker file

whisperx/alignment.py
Resolves issue #153
See also this [Google Colab](https://colab.research.google.com/drive/1SeI2PLs4B7H53oBkZrVPO0MLWTjZ6gcI)
=> Enable Hebrew support

whisperx/asr.py
=> Fix tuple unpacking

whisperx/asr.py
This adds keywords language and task as proposed in #241
We drop the `del_tokenizer` boolean and instead just keep the most recent options for our tokenizer.
=> Add transcribe keywords

whisperx/alignment.py
Added a korean wav2vec2 model.
tested and seems to be working well.
=> added Korean wav2vec2 model

whisperx/asr.py
The `faster_whisper.WhisperModel` also takes `download_root` as one of the optional parameters. I just added the same to `whisperx.load_model`.
=> Added download path parameter.

whisperx/transcribe.py
Changed the description of the `batch_size` parameter.
=> Update transcribe.py -> small change in `batch_size` description

README.md, whisperx/diarize.py, whisperx/transcribe.py
solves the issue in: https://github.com/m-bain/whisperX/issues/399
=> make diarization faster

whisperx/asr.py
=> add temperature loop with fallback and pass **kwargs to model.generate

whisperx/utils.py
=> fix writer fail on segments 0

whisperx/utils.py
Fixed missing the speaker part when enable --highlight_words
=> fix missing speaker prefix

whisperx/SubtitlesProcessor.py, whisperx/conjunctions.py
Example usage: 
subtitles_proccessor = SubtitlesProcessor(output["segments"], detected_language, max_line_length = 50, min_char_length_splitter = 35) subtitles_proccessor.save("subtitles.srt", advanced_splitting = True)
=> A solution to long subitles and words without timestamps

whisperx/asr.py, whisperx/transcribe.py
=> add faster whisper threading

requirements.txt
Closes #469 
PR #458 added new options that are necessary for newer versions, but are not compatible for older.
=> pin faster whisper

whisperx/alignment.py
=> fix: ZeroDivisionError when --print_progress True

whisperx/alignment.py
torchaudio wav2vec2 require a minimum input length of 400 samples to avoid the following error:
```python
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
```
which might not be the case always so I handled this case, note that this doesn't affect the result as the extra padding is ignored using the attention mask as mentioned [Here](https://pytorch.org/audio/main/generated/torchaudio.models.Wav2Vec2Model.html)
=> fix minimum input length for torch wav2vec2 models

whisperx/diarize.py
Fixes https://github.com/m-bain/whisperX/issues/497
On empty tracks create an empty dataframe with correct number of columns.
=> fix(diarize): key error on empty track

whisperx/asr.py, whisperx/transcribe.py
Fixes https://github.com/m-bain/whisperX/issues/524
=> Pass patience and beam_size to faster-whisper.

whisperx/asr.py
As the param - model in load_model is not used in function, modify to make it can be passed in.
=> Update asr.py and make the model parameter be used

whisperx/alignment.py
Hello!
I just added an alignment model for catalan language from:
https://huggingface.co/softcatala/wav2vec2-large-xlsr-catala
Softcatala is a renowned organization in Catalonia and widely used for translations. This is why I have chosen this wav2vec model from huggingface
I have tested it and it is working well.
Thank you!
David Martin Rius
=> Add align model for catalan language.

setup.py, whisperx/diarize.py
Close #499 
Pyannote now fully can work with faster_whisper and on GPU
Do not forget to ask permission for new weights access on hunggingface : https://huggingface.co/pyannote/speaker-diarization-3.1
=> Update pyannote to 3.1.0

requirements.txt
Minimal change to let pip install requirements
=> pip compliance for git+ installs

whisperx/alignment.py
- Added the phoneme based model `https://huggingface.co/gvs/wav2vec2-large-xlsr-malayalam`, which is most popular wav2vec model available in huggingface
=> Add alignment model for Malayalam

whisperx/alignment.py
I just added alignment models for three other languages:
https://huggingface.co/comodoro/wav2vec2-xls-r-300m-sk-cv8
https://huggingface.co/anton-l/wav2vec2-large-xlsr-53-slovenian
https://huggingface.co/classla/wav2vec2-xls-r-parlaspeech-hr
=> Update alignment.py - added alignment for  sk and sl languages

whisperx/alignment.py
Adds support for Romanian by adding Romanian phoneme-based ASR model 
https://huggingface.co/gigant/romanian-wav2vec2
Based on its HF Model Card, this model has better evaluations than 
https://huggingface.co/anton-l/wav2vec2-large-xlsr-53-romanian
=> Added Romanian phoneme-based ASR model

whisperx/alignment.py
New `wav2-vec` models are going to be added for current languages that are supported for transcriptions:
- **Basque** from [stefan-it/wav2vec2-large-xlsr-53-basque](https://huggingface.co/stefan-it/wav2vec2-large-xlsr-53-basque)
- **Galician** from [ifrz/wav2vec2-large-xlsr-galicia](https://huggingface.co/ifrz/wav2vec2-large-xlsr-galician)
- **Georgian** from [xsway/wav2vec2-large-xlsr-georgian](https://huggingface.co/xsway/wav2vec2-large-xlsr-georgian)
@m-bain
=> Feat: add new align models - SHORT

.github/workflows/build-and-release.yml, .gitignore, MANIFEST.in
This PR adds a workflow to automate building and releasing a new wheels version to PyPi and GH Releases.
It will be triggered when a new version is released in GitHub.
=> chore: add build and release workflow

whisperx/asr.py
vad_method is `None` by default, so `pyannote` should be chosen by default in this case?
=> fix vad_method is none

whisperx/vads/pyannote.py
@m-bain leaving this open for a few days in case you still want to keep it for later.
Closes #449
=> chore: remove deprecated VAD_SEGMENTATION_URL

whisperx/alignment.py, whisperx/utils.py
Adds [wav2vec2-large-xlsr-latvian-cv](https://huggingface.co/jimregan/wav2vec2-large-xlsr-latvian-cv) model for Latvian, tested and working correctly.
=> feat: add Latvian align model

whisperx/alignment.py
This reverts commit 0d9807adc55a0ba7de8811ca9c9c0c33865e6bb3.
=> Revert "feat: add Basque alignment model (#1074)"

whisperx/SubtitlesProcessor.py, whisperx/__init__.py, whisperx/__main__.py, whisperx/alignment.py, whisperx/asr.py, whisperx/audio.py, whisperx/diarize.py, whisperx/transcribe.py, whisperx/vads/__init__.py, whisperx/vads/pyannote.py
=> refactor: update import statements to use explicit module paths

README.md, pyproject.toml, whisperx/__init__.py, whisperx/__main__.py, whisperx/transcribe.py
Changes introduced by this PR:
* refactored CLI entry point from (transcribe.cli to __main__.cli)
* refactored imports for lazy loading
=> feat: improve CLI loading speed by lazy loading public API
