README.md, whisperx/__init__.py, whisperx/transcribe.py
What it is: Parallalize the `transcribe` function. It gives at least 2X speedup on transcribing.
TODO: supporting temperature sweeping under batch processing.
=> support batch processing

whisperx/alignment.py
Fixed the bug which causes failure in alignment when the voice input is too small or has only 1 segment by fixing a value if it doesn't exist.
=> added if clause for checking 'level-1'

whisperx/transcribe.py
This change aims at improving the transcription timestamps accuracy when an audio file starts with a silence. Instead of using the beginning of the audio file with the VAD (as it is currently implemented), we use the first voice activity detection as our starting point.
=> Improvement to transcription starting point with VAD

whisperx/transcribe.py
This PR allows for GPU acceleration when using VAD filters.
whisperX's VAD filter always infers on CPU.
In whisperx/transcribe.py, `pyannote.audio.Inference` is not passed `device` argument.
You can see the devices used for inference as follows:
```
$ python
Python 3.10.7 (main, Nov 13 2022, 02:27:45) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import torch
>> torch.cuda.is_available()
True
>>> from pyannote.audio import Inference
>>> vad_pipeline = Inference("pyannote/segmentation")
>>> vad_pipeline.model.device
device(type='cpu')
```
When tested on a 22 minutes and 20 seconds audio file, the process took 4 minutes and 27 seconds before the modification and 1 minute and 49 seconds after the modification. The processing time was reduced …
=> GPU acceleration when using VAD filters

whisperx/alignment.py
- removed use of walrus operator in favor of `np.cumsum`
- fixes #92 
Seems to work fine, tested the examples from the readme on Docker image `python:3.7-slim-bullseye` and the results are identical.
=> Added Python 3.7 compatibility

requirements.txt
python-soundfile now supports mp3 files since [v0.12.0](https://github.com/bastibe/python-soundfile/releases/tag/0.12.0.) 
closes #41
=> fix: force soundfile version update for mp3 support

whisperx/transcribe.py
Model should be loaded with an id to avoid this error: huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'pyannote\segmentation'.
#113
=> Fix hugging face error

requirements.txt
WhisperX is downloading the PyPi package [whisper](https://pypi.org/project/whisper/) instead of [openai-whisper](https://pypi.org/project/openai-whisper/), which results in an error
=> Fix Requirements

requirements.txt, setup.py, whisperx/asr.py, whisperx/audio.py, whisperx/diarize.py, whisperx/transcribe.py
This will update `torch` and `torchaudio` to versions `2.0.0` and `2.0.1`. Additionally, we fetch `pyannote` directly from it's development branch - this is currently the only way to enable support for `torch` version 2.
There are a few drawbacks with using the development branch:
- While it is the default branch of `pyannote`, it is not as stable as a release
- Any breaking changes that occur (and they can) will break `whisperX`
- The VAD model is not automatically updated and might not work as well with newer versions of `pyannote`
- We will generate some warnings on loading the VAD model as mentioned in [this issue](https://github.com/pyannote/pyannote-audio/issues/1342) at `pyannote's` repo
So instead of using the development branch, I would propose two other options
1. Use pip to …
=> Update pyannote and torch version

whisperx/alignment.py, whisperx/asr.py, whisperx/types.py
Since I did this for my local project using parts of WhisperX, I added typing support to the different result types of transcription and alignment. I can extend it for Diarization if you want but since I didn't need it for my project I'd only add it if you're interested in it. Otherwise I'll just close the PR again.
=> Add custom typing for results

whisperx/asr.py, whisperx/transcribe.py
Regarding #228 this will add a `--device_index` flag.
Right now it is not possible to specify a list of indices, even though the original faster-whisper supports this since I can't tell how well this behaves with the custom batch inference.
This PR will fail if the specified device index does not exist.
Expected error:
> File "/content/whisper-env/lib/python3.10/site-packages/whisperx/asr.py", line 32, in load_model
model = WhisperModel(whisper_arch, device=device, device_index=device_index, compute_type=compute_type)
File "/content/whisper-env/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 120, in __init__
self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error invalid device ordinal
=> Add device_index option

whisperx/alignment.py
This PR adds the following Czech alignment model: https://huggingface.co/comodoro/wav2vec2-xls-r-300m-cs-250.
I have successfully tested this with several Czech audio recordings with length of up to 3 hours, and the results are satisfactory.
However, I have received the following warnings and I am not sure how relevant it is:
```
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file C:\Users\Thebys\.cache\torch\whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0. Bad things might happen …
```
=> Add Czech alignment model

whisperx/alignment.py
Added default model for Vietnamese.
Because I use Google Colab I added the model https://huggingface.co/nguyenvulebinh/wav2vec2-base-vi and it works pretty well.
=> Add war2vec model for Vietnamese

whisperx/types.py
Fix in types
1. list --> Typing.List
Error Because of this
```bash
File "/opt/conda/lib/python3.8/site-packages/whisperx/types.py", line 41, in SingleAlignedSegment
words: list[SingleWordSegment]
TypeError: 'type' object is not subscriptable
```
=> fix: Bug  in type  hinting

whisperx/transcribe.py, whisperx/utils.py
Hi,
I wanted to check if the transcript produced by WhisperX had improved for French compared to the first time I tested it. And it has ... tremendously! This works really great. 
So I needed to check it in Audacity, that's why I made this export and I propose it now to the community. 
This exports the transcript to a text file that can be directly imported in Audacity as label file. This is useful to visually check the transcript-audio alignment.
To use it, fire up Audacity, then do "Import Labels" with this file.
=> Add Audacity export

README.md
This is listed as a requirement but isn't used in the project. If you try to pull it in, you'll get a dep conflict.
=> Remove torchvision from README

README.md
Hey @m-bain, this is some really fantastic work; the performance you've been able to get out of Whisper is incredible. 
I've put a demo of [WhisperX up on Replicate](https://replicate.com/daanelson/whisperx); it's under my name at the moment but lmk if you're interested and I can transfer it to you. This PR adds a link to the demo on Replicate - can change the wording if you'd like. 
Happy to also add the [code it uses](https://github.com/daanelson/cog-whisperx) which automatically containerizes WhisperX if you're interested - I know some folks find that useful but also understand wanting to keep your repo uncluttered.
=> adding link to Replicate demo

README.md
This prevents CuFFT errors on newer cards such as the RTX 4090 and RTX 6000 Ada.
fixes #254
=> Suggest using pytorch-cuda 11.8 instead of 11.7

README.md
- I have created an additional replicate instance of whisperX using the medium model.
-  For me, the medium model dramatically reduces the likelihood of whisperX switching to other languages (like Spanish) when transcribing a non-native English speaker.
=>  adds link to whisperX medium on replicate.com

whisperx/asr.py, whisperx/transcribe.py
Suggest from https://github.com/m-bain/whisperX/issues/200#issuecomment-1666507780
This PR add a argument `chunk_size` with `int` input
Default is 30, reduce this if the chunk is too long.
```
whisperx --chunk_size 30 audio.wav
```
The length of sentences in different languages varies. I believe it is reasonable to extract the chunk_size as a parameter. 
In the case of Chinese and Japanese, the suggested value of 5~10 (by @seset) is relatively appropriate. You can clearly see the difference in the following image.
| chunk size 6 | chunk size 30 |
|-|-|
|![2023-08-29 23 46 52](https://github.com/m-bain/whisperX/assets/16995691/b98f320a-085a-41be-9b07-b34ace5a2186)|![2023-08-29 23 47 28](https://github.com/m-bain/whisperX/assets/16995691/c3ab31db-c8d6-46dd-9472-f1bc323013a8)|
=> feat: Add merge chunks chunk_size as arguments.

whisperx/transcribe.py, whisperx/utils.py
This PR should fix #248 and fix #310
I discovered that the issue lies in SubtitlesWriter, as it is joining words with white space which is not appropriate for ja and zh.
=> chore(writer): Join words without spaces for ja, zh

whisperx/utils.py
Currently, certain utf-8 characters will be saved in `\uxxx` format in the `.json` file, for example, the japanese characters. This makes it hard for developers to inspect the most complete output of whisperx.
The commit will encode the related characters in their original format
=> chore(writer): improve text display(ja etc) in json file

whisperx/alignment.py
In a #510 I fixed the minimum input length problem and so I don't see a reason why we can't align short segments that are often consisting of a single word
=> remove the minimum length for alignment and print the failing segment

setup.py
https://github.com/m-bain/whisperX/issues/540
Breaks Mac platform and arm64 platforms. 
Tested by successfully building on my m1 mac doing:
pip install .
And also using Depot (a way to build Dockerfiles remotely, using arm64):
depot build -t whisperx_image . --platform linux/arm64 --load
=> Update setup.py to download pyannote depending on platform

whisperx/transcribe.py, whisperx/utils.py
Some minor fixes I noticed when I was making changes for [https://github.com/m-bain/whisperX/pull/548]()
- Removed references to **--word-timestamps** as it's not a valid option in WhisperX. Rephrased to **(not possible with --no_align)** as word options need the word segments that are generated when doing the alignment. **PLEASE CORRECT ME IF I'M WRONG.**
- Removed some duplicated code.
=> Minor fixes for word options and subtitles

whisperx/vad.py
Should resolve #511 
I'm not 100% happy with my solution but usually t should be overridden. If it's not we are talking about such a short audio that there is no reasonable way to handle alignment.
=> fix unboundlocalerror

requirements.txt, whisperx/audio.py
I think it would be better to drop ffmpeg-python dependency like whiseper.
- https://github.com/openai/whisper/pull/1242
The main reason is the library is not maintained.
=> Drop ffmpeg-python dependency and call ffmpeg directly.

whisperx/alignment.py
Words already were not aligned based on the end of space characters, this was still the case for the whole segment. As such, 
```bash
ffmpeg -i "https://mediandr-a.akamaihd.net/progressive/2022/1118/TV-20221118-2201-5200.ln.mp4" -ac 1 -ar 16000 test.wav
whisperx test.wav --model small --compute_type="float32" --language "de"
``` 
yielded 
```json
{"start": 1.178, "end": 4.5, "text": " Der Traum vom Rekordschiff Made in Mecklenburg-Vorpommern.", "words": [{"word": "Der", "start": 1.178, "end": 1.318, "score": 0.945}, {"word": "Traum", "start": 1.358, "end": 1.598, "score": 0.893}, {"word": "vom", "start": 1.638, "end": 1.878, "score": 0.962}, {"word": "Rekordschiff", "start": 1.938, "end": 2.679, "score": 0.776}, {"word": "Made", "start": 2.719, "end": 2.919, "score": 0.83}, {"word": "in", …
```
=> no align based on space

whisperx/asr.py
Fixing the https://github.com/m-bain/whisperX/issues/583.
We should define `load_model()` after defining WhisperModel.
=> Move load_model after WhisperModel

README.md
Updates the README to link to the correct version of pyannote, since it seemed to only work when I agreed to the version 3.1 terms
Can confirm version 3.1 is much faster, my own benchmark from today:
Machine: RTX 3060 12GB, Xeon E5-2698 v3
Time for running whisperx with `--diarize` flag on 5min mp3:
With pyannote version 3.0: 164 seconds
With pyannote version 3.1: 45-60 seconds
Speedup: 3-4x
I could remove the README warning about using version 3.0, or maybe it's good to leave it for those who haven't pulled lately?
Best regards,
Sean
PS:
Thanks to the maintainer for their ongoing support and to @remic33 for their recent update with the new pyannote version. Apologies for spamming multiple commit references in the original PR caused by pushes to my fork. Was unaware of this GitHub …
=> Update README to correct speaker diarization version link

whisperx/alignment.py
Adding Wav2Vec2-models for Norwegian Bokmål and Norwegian Nynorsk. The models are testet together with WhisperX, and works great. For Bokmål I have added the 1B model, even if I see fairly little difference between that and the 300M model. For Norwegian Nynorsk only a 300M model exist. The quality of the Wav2Vec models are also reported here: https://arxiv.org/abs/2307.01672
=> Adding Norwegian Bokmål and Norwegian Nynorsk

README.md
Hello,
I wanted to add a link to a Replicate model I made in the README of this project. The differences between this model and the previous ones are that it uses the large-v3 model, and it accepts more input parameters to customize inference (you can set the language, the initial prompt, VAD parameters, activate diarization and set parameters for it).
=> Add Replicate large-v3 demo

requirements.txt
Fix #715
As pointed out in #715, the current requirements.txt fails to install faster-whisper. Additionally, as mentioned in https://github.com/m-bain/whisperX/pull/710#issuecomment-1959400388, the PyPI version of faster-whisper has already been updated, and there is no longer a need to install directly from GitHub.
=> fix: update faster-whisper dependencies

requirements.txt
Force ctranslate to version 4.4.0 due libcudnn_ops_infer.so.8: https://github.com/SYSTRAN/faster-whisper/issues/729
=> fix: force ctranslate to version 4.4.0

whisperx/asr.py, whisperx/transcribe.py
https://github.com/m-bain/whisperX/issues/738
had the issue with non-functionality of verbose flag and suggested handling it like openai-whisper
Quote from https://github.com/m-bain/whisperX/issues/738
```
In the orginal Openai-Whisper in Python you can set verbose=True, e.g.
result = model.transcribe(input_file,
language='en',
initial_prompt=prompt,
fp16=False,
verbose=True)
This prints the transcription output as the program runs so you can observe any errors in the transcription before it finalises, e.g.
[00:00.000 --> 00:07.000] Okay.
[00:30.000 --> 00:43.680] I'm making inquiries into a workplace dispute that
[00:43.680 --> 00:50.160] has reportedly occurred on Saturday 6 January
[00:50.160 --> 00:51.160] 2024.
Judging from what I can see in transcribe.py, WhisperX has verbose=True …
```
=> Add ultization to verbose flag

whisperx/asr.py
Adds the parameter local_files_only (default False for consistency) to whisperx.load_model so that the user can avoid downloading the file and return the path to the local cached file if it exists.
=> Added local_files_only option on whisperx.load_model for offline mode

whisperx/alignment.py
This change makes "model_dir" the cache directory for Wav2Vec2 models as well
=> adding cache_dir to wav2vec2

.github/workflows/python-compatibility.yml, setup.py
This PR adds a very basic workflow to test the installation of whisperX on various Python versions. This is useful when modifying dependencies and bumping versions.
This PR also removes support for Python 3.8 which is officially EOL and unsupported by the pyannote.audio version we're using.
=> feat: add basic installation test flow & restrict python versions

setup.py
Fixed UnicodeDecodeError when installing package on Windows systems by explicitly setting UTF-8 encoding when reading README.md file.
When installing the package on Windows, the setup.py script fails with a UnicodeDecodeError because it tries to read README.md using the default system encoding (cp1252) which can't handle some special characters.
Added explicit UTF-8 encoding when opening README.md file.
=> fix: add UTF-8 encoding when reading README.md

whisperx/utils.py
This PR adds the missing speaker tag for txt output in --diarize mode.
closes #801
=> feat: include speaker information in  WriteTXT when diarizing

whisperx/asr.py
ISSUE: In faster_whisperer 1.1.0, TranscriptionOptions was changed from a NamedTuple to a Dataclass leading to a bug in .transcribe when using suppress_numerals. The bug arises with the self.options._replace method which does not exist for the dataclasses object.
FIX: Instead we can import replace from dataclasses and using that function instead allows us to update the transcriptionOptions and successfully transcribe. 
Error:
result = model.transcribe(audio, batch_size=self.batch_size, language=self.language)
File /anaconda/envs/w/lib/python3.10/site-packages/whisperx/asr.py:213, in FasterWhisperPipeline.transcribe(self, audio, batch_size, num_workers, language, task, chunk_size, print_progress, combined_progress, verbose)
211     new_suppressed_tokens = numeral_symbol_tokens + …
=> Bug Fix: Suppress Numerals dataclasses replace method

README.md, whisperx/__init__.py, whisperx/asr.py, whisperx/transcribe.py, whisperx/vads/__init__.py, whisperx/vads/pyannote.py, whisperx/vads/silero.py, whisperx/vads/vad.py
Implementation includes:
- Extension of WhisperX to accept multiple VAD alternatives that do not have to necessarily emerge from `pyannote-audio` toolkit. 
- [Silero VAD](https://github.com/snakers4/silero-vad) as an alternative VAD option.  
- Fix in `whisperx\__init__.py` imports.
The implementation aims to respect the current structure as well as keep the existing functionality intact. It is worth mentioning that the manually-assigned `vad_model` still works as expected (see `load_model` for details). 
See  relevant issue for further details. resolves https://github.com/m-bain/whisperX/issues/889
- pyannote and silero cases both tested on CPU & GPU setups without an issue (current silero vad implementation utilizes only CPU)
- Also tested using manually assigned vad_model (manually …
=> Silero VAD support 

README.md
The list of languages is no longer in transcribe.py, it’s been moved to alignment.py. I have created a new permalink.
I would suggest another change: remove
> , and use the wihisper `--model large`
from line 141. It seems to work with `--model small` just as well. But I am not sure why it was there in the first place, so I haven’t included the change in this PR.
=> Update links to language models in README

whisperx/vads/silero.py
When `vad_method=silero` and no active speech found in audio an `IndexError: list index out of range` occurs.
https://github.com/m-bain/whisperX/blob/355f8e06f7299e9761f16e7bf9e40ce9a05f2157/whisperx/vads/vad.py#L32
This repo handles empty segments_list case in silero with the style used in pyannote, preventing errors.
=> chore: handle empty segments_list case in silero

whisperx/vads/silero.py
Hello,
Correcting the previous error, the variable `segments` has been renamed to `segments_list` to maintain consistency across the codebase. For more context, please refer to the discussion in https://github.com/m-bain/whisperX/pull/1005.
=> chore: fix variable naming inconsistency from `segments` to `segments_list`

whisperx/transcribe.py
For running whisperx offline (prior discussion here https://github.com/m-bain/whisperX/issues/263) we need to tell whisperx to not attempt to download any models.
This functionality already existed in the load_model function, this PR simply adds a CLI parameter to expose the setting.
=> Add models_cache_only param

whisperx/alignment.py
---
I noticed that there was no existing **phoneme-based ASR model** specifically for the **Tagalog language**, so I explored available models on **Hugging Face**. After testing one, I found that it performed well, providing **accurate timing from the segment level down to the word level**.  
🔗 **Model:**  [Khalsuu/filipino-wav2vec2-l-xls-r-300m-official](https://huggingface.co/Khalsuu/filipino-wav2vec2-l-xls-r-300m-official)
To evaluate the model’s performance, I tested it using a **YouTube video**:  
📺 **Video Link:** [Watch here](https://www.youtube.com/watch?v=RrbttqG6DX0)
I also developed a **Notebook** to convert the transcriptions into **SRT format** for further analysis.  
👾 **Alignment Preview:**  
I tested the **SRT output** by overlaying it onto the video. The evaluation was …
=> Added Phoneme-Based ASR Model for Tagalog

whisperx/alignment.py
The following PR adds a phoneme-based alignment model for Basque language.
As a result we obtain high-precision word-level timestamps.
Demo: https://youtu.be/adB62l_PdYA
Thanks
=> Basque alignment model

whisperx/asr.py
The hotwords argument exists but isn't passed to faster-whisper, this PR allows us to use hotwords
=> feat(hotwords): Pass hotwords option to faster-whisper

whisperx/utils.py
`utils.py` contains a duplicated dictionary item, which should be removed.
"lv": "latvian"
=> Remove duplicated item

pyproject.toml, uv.lock, whisperx/transcribe.py
This has been tested on Google Colab with 3.10 & 3.11 and worked as it used to.
YMMV, but I also had to run `apt-get install libcudnn8 libcudnn8-dev` after installing whisperx.
=> fix: resolve dependency issues

whisperx/__main__.py, whisperx/diarize.py, whisperx/transcribe.py
Removing the hardcoded value from `diarization` so we can take it from the environment with `DIARIZATION_MODEL_CONFIG` but also keeping the original default `pyannote/speaker-diarization-3.1`
=> feat: diarization model env config

whisperx/alignment.py
**Bug Fix: IndexError in `alignment.py` when running alignment**
**Problem**
Sometimes when running alignment with WhisperX, I got this error:
```shell
IndexError: tensors used as indices must be long, int, byte or bool tensors
```
This happens in `alignment.py` at line 427:
```python
regular_scores = frame_emission[tokens.clamp(min=0)]
```
Looks like tokens can sometimes be a float tensor, but PyTorch only accepts integer types for indexing.
**How I fixed it**
I just added `.long()` to make sure it’s using integer indices:
```python
regular_scores = frame_emission[tokens.clamp(min=0).long()]
```
Pretty small change, but it fixes the crash.
**Notes**
- This bug is **intermittent** — doesn’t happen all the time.
- I ran into it while transcribing a Chinese audio file using `large-v2`.
- …
=> Fix: Ensure integer tensor indexing in get_wildcard_emission() to avoid IndexError

whisperx/alignment.py
The alignment code was creating an empty `PunktParameters()` object and only setting a few hardcoded abbreviations, which bypassed all of NLTK Punkt's pre-trained model. This could cause incorrect sentence splitting (e.g., "Richard Jr." | "went home" instead of "Richard Jr. went home"),leading to alignment failures and inaccurate word-level timestamps.
Use Punkt's pre-trained English model with all it's abbreviations and trained sentence boundary detection.
> [!NOTE]
Currently uses English Punkt model for all languages. Could be improved with language-specific models.
=> feat: use pre-trained Punkt model instead of empty parameters
